format = """\
  $battery\
  $time\
  $username\
  $shell\
  $directory\
  $package\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $cmd_duration\
  $line_break\
  $jobs\
  $character\
  """

[battery]
full_symbol = ""
discharging_symbol = "•" # ""
charging_symbol = ""
unknown_symbol = "" # ""
format = "[$symbol$percentage]($style) "

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 80
style = "bold green"

[[battery.display]]
threshold = 100
style = "bold yellow"

[time]
disabled = false
format = "[$time]($style) - "
style = "cyan"

[username]
show_always = true
style_user = "blue"

[shell]
format = "\\[$indicator\\] "
powershell_indicator = "pwsh"
bash_indicator = "bash"
# unknown_indicator = "cmd"
disabled = false

[directory]
truncate_to_repo = true
read_only = ""
truncation_symbol = "…/"

[package]
display_private =	true
symbol = " "

[git_branch]
symbol = " "

[git_commit]
style = "bold white"
tag_symbol = "笠 "
tag_disabled = false

[git_status]
conflicted = "= "
ahead = "⇡×${count} "
behind = "⇣×${count} "
diverged = "${ahead_count}×⇕×${behind_count} "
untracked = "?×${count} "
stashed = "\\$×${count} "
modified = "!×${count} "
staged = "+×${count} "
renamed = "»×${count} "
deleted = "✘×${count} "

# [memory_usage]
# format = "$symbol[${ram}( | ${swap})]($style) "
# show_percentage = true
# show_swap = true
# threshold = -1
# symbol = " "
# style = "bold dimmed white"
# disabled = false

[aws]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

# [haskell]
# symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
