format = """\
  $battery\
  $time\
  $username\
  $env_var\
  $shell\
  $directory\
  $package\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $cmd_duration\
  $line_break\
  $jobs\
  $character\
  """

[battery]
full_symbol = "•"
discharging_symbol = ""
charging_symbol = ""
unknown_symbol = "!"
format = "[$symbol$percentage]($style) "

[[battery.display]]
threshold = 20
style = "italic red"

[[battery.display]]
threshold = 80
style = "italic green"

[[battery.display]]
threshold = 100
style = "italic yellow"

[time]
disabled = false
format = "[$time]($style) - "
style = "italic cyan"

[env_var.WSL_DISTRO_NAME]
format = "[$env_value]($style) "
style = "underline purple"

[env_var.MSYSTEM]
format = "[$env_value]($style) "
style = "underline purple"

[shell]
format = "\\[$indicator\\] at "
powershell_indicator = "[pwsh](bold blue)"
zsh_indicator = "[zsh](bold blue)"
bash_indicator = "[bash](bold blue)"
unknown_indicator = "[cmd](bold blue)"
disabled = false

[directory]
truncate_to_repo = true
read_only = " "
truncation_symbol = "…/"

[package]
symbol = " "

[git_branch]
style = 'italic purple'
symbol = " "

[git_commit]
style = "bold white"
tag_symbol = "笠 "
tag_disabled = false

[git_status]
conflicted = "= "
ahead = "⇡×${count} "
behind = "⇣×${count} "
diverged = "${ahead_count}×⇕×${behind_count} "
untracked = "?×${count} "
stashed = "\\$×${count} "
modified = "!×${count} "
staged = "+×${count} "
renamed = "»×${count} "
deleted = "✘×${count} "

# [memory_usage]
# format = "$symbol[${ram}( | ${swap})]($style) "
# show_percentage = true
# show_swap = true
# threshold = -1
# symbol = " "
# style = "bold dimmed white"
# disabled = false

[aws]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

# [haskell]
# symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
