[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-parent"
desc = "Show or hide the parent pane"

[[mgr.prepend_keymap]]
on   = "Z"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell pwsh --block'
desc = "Open PowerShell here"

[[mgr.prepend_keymap]]
on   = [ "p", "<Space>" ]
run  = 'shell -- qlmanage -p "$@"'
for  = 'macos'
