use_nerdfont = true
flip_status_indicators = true

[theme]
background = "default"
primary = "white"
secondary = "light black"
title = "green"
playing = "green"
playing_selected = "red"
playing_bg = "black"
highlight = "light white"
highlight_bg = "light blue"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "white"
cmdline_bg = "black"
search_match = "light red"

[keybindings]
"Shift+p" = "move playing"
"p" = "queue"
"Space" = "playpause"
